export const navItems = [
	{
		title: 'Switch Organization',
		icon: '/icons/briefcase.svg',
		link: '/dashboard',
		id: 1,
	},
	{
		title: 'Dashboard',
		icon: '/icons/home.svg',
		link: '/dashboard',
		id: 2,
	},
	{
		title: 'CUSTOMERS',
		header: true,
		link: '/dashboard',
		id: 3,
	},
	{
		title: 'Users',
		icon: '/icons/user-friends.svg',
		link: '/dashboard',
		id: 4,
	},
	{
		title: 'Guarantors',
		icon: '/icons/users.svg',
		link: '/dashboard',
		id: 5,
	},
	{
		title: 'Loan',
		icon: '/icons/sack 1.svg',
		link: '/dashboard',
		id: 6,
	},
	{
		title: 'Decision Models',
		icon: '/icons/handshake-regular 1.svg',
		link: '/dashboard',
		id: 7,
	},
	{
		title: 'Savings',
		icon: '/icons/piggy-bank 1.svg',
		link: '/dashboard',
		id: 8,
	},
	{
		title: 'Loan Requests',
		icon: '/icons/Group 104.svg',
		link: '/dashboard',
		id: 9,
	},
	{
		title: 'Whitelist',
		icon: '/icons/user-check 1.svg',
		link: '/dashboard',
		id: 10,
	},
	{
		title: 'Karma',
		icon: '/icons/user-times 1.svg',
		link: '/dashboard',
		id: 11,
	},
	{
		title: 'BUSINESS',
		header: true,
		link: '/dashboard',
		id: 12,
	},
	{
		title: 'Organization',
		icon: '/icons/briefcase.svg',
		link: '/dashboard',
		id: 13,
	},
	{
		title: 'Loan Products',
		icon: '/icons/Group 104.svg',
		link: '/dashboard',
		id: 14,
	},
	{
		title: 'Savings Products',
		icon: '/icons/savings.svg',
		link: '/dashboard',
		id: 15,
	},
	{
		title: 'Fees and Charges',
		icon: '/icons/coins-solid 1.svg',
		link: '/dashboard',
		id: 16,
	},
	{
		title: 'Transactions',
		icon: '/icons/icon.svg',
		link: '/dashboard',
		id: 17,
	},
	{
		title: 'Services',
		icon: '/icons/galaxy 1.svg',
		link: '/dashboard',
		id: 18,
	},
	{
		title: 'Service Account',
		icon: '/icons/user-cog 1.svg',
		link: '/dashboard',
		id: 19,
	},
	{
		title: 'Settlements',
		icon: '/icons/scroll 1.svg',
		link: '/dashboard',
		id: 20,
	},
	{
		title: 'Reports',
		icon: '/icons/chart bar 2.svg',
		link: '/dashboard',
		id: 21,
	},
	{
		title: 'SETTINGS',
		header: true,
		link: '/dashboard',
		id: 22,
	},
	{
		title: 'Preferences',
		icon: '/icons/sliders-h 1.svg',
		link: '/dashboard',
		id: 23,
	},
	{
		title: 'Fees and Pricing',
		icon: '/icons/badge-percent 1.svg',
		link: '/dashboard',
		id: 24,
	},
	{
		title: 'Audit Logs',
		icon: '/icons/clipboard-list 1.svg',
		link: '/dashboard',
		id: 25,
	},
];

export const usersStats = [
	{
		title: 'Users',
		icon: '/icons/user-stat-icon-1.svg',
		count: '2,453',
	},
	{
		title: 'Active Users',
		icon: '/icons/user-stat-icon-2.svg',
		count: '2,453',
	},
	{
		title: 'Users with loans',
		icon: '/icons/user-stat-icon-3.svg',
		count: '12,453',
	},
	{
		title: 'Users with savings',
		icon: '/icons/user-stat-icon-4.svg',
		count: '102,453',
	},
];